substitutions:
  name: olimex-bluetooth-proxy
  friendly_name: Bluetooth Proxy

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

api:
  encryption:
    key: "xu+4kolIDtjuhBX5ACIwzyReQP3u8mIGVvKxrZ9yNXI="

logger:
ota:

dashboard_import:
  package_import_url: github://esphome/jcortenbach/bluetooth-proxies/olimex-esp32-poe-iso.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

ble_client:
  - mac_address: 78:A5:04:3F:A0:28
    id: anova_sous_vide
    
climate:
  - platform: anova
    name: "Anova Sous Vide"
    ble_client_id: anova_sous_vide
    unit_of_measurement: c
